config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
  get 'members/index'
  get 'welcome/index'
  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :candidates do
    member do
      post :vote
    end
  end
  resources :welcomes, only: [:index]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    # member do
      # post :comment
    # end
  end
  resources :plans do
    member do
      post :confirm
      # post :cancelled
      post :join
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :members do
    member do
      get :drafts
      post :change_role
      # post :add_friend
      # post :unfriend
      # post :accept
      # post :ignore
    end
  end
  post "/members/:member_id/plans/:plan_id", to: "members#invite", :as => :invite
  post "/members/:member_id/plans/:plan_id", to: "plans#join", :as => :join
  post "/members/:member_id/plans/:plan_id", to: "members#cancelled", :as => :cancelled

  resources :friendships, only: [:create, :destroy] do
    member do
      post :cancelled
      post :accept
      post :ignore
    end
  end

  root "welcomes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates_presence_of :name, :age, :party, :politics
  has_many :vote_logs, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of  :content
  belongs_to :commentable, :polymorphic => true
  belongs_to :member
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: "Member"
  validates :friend_id, uniqueness: { scope: :member_id }
end

app/models/invite_plan.rb
class InvitePlan < ApplicationRecord
  # validates :member_id, uniqueness: { scope: :plan_id }

  belongs_to :member
  belongs_to :plan
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :plans
  has_many :posts, dependent: :destroy
  
  has_many :comments
  has_many :comments_post, through: :comments, source: :post
  
  # owner 邀請使用者，status: false
  has_many :invite, -> {where status: false}, class_name: "InvitePlan"
  # user 拿到邀請他的 plan，status: false
  has_many :invited_plans, through: :invite, source: :plan

  # user 想加入
  has_many :join, -> {where status: false}, class_name: "InvitePlan"
  # user 想加入
  has_many :join_plan, through: :join, source: :plan


  
  # user been invite
  def invited_plans?(plan)
    self.invited_plans.include?(plan)
  end

  def join_plan?(plan)
    self.join_plan.include?(plan)
  end
  

  # Friendship 的資料表紀錄，menber 是送出邀請的人，friend_id 是被邀請的人。

  # member_id如果是自己，就會去拿 friend_id，並且status 要是 true，的用戶出來
  has_many :friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "member_id", dependent: :destroy
  has_many :friends, through: :friendships
  
  # 從friend_id 如果是自己，就會去拿 member_id出來，並且status 要是 true，的用戶出來
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :member

  # 使用 wait_accept_friendships 送出 create 好友邀請。
  # member_id 如果是自己，就去拿 friend_id，並且status 要是 false，的用戶出來
  has_many :wait_accept_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "member_id", dependent: :destroy
  has_many :waiting_for_accept, through: :wait_accept_friendships, source: :friend
  
  # friend_id 如果是自己，就會去拿 member_id出來，並且status 要是 false，的用戶出來
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friends_request, through: :request_friendships, source: :member

  def all_friends
    (friends + inverse_friends).uniq
  end

  def waiting_for_accept?(member)
    self.waiting_for_accept.include?(member)
  end

  def friends_request?(member)
    self.friends_request.include?(member)
  end

  def friends?(member)
    self.friends.include?(member) || self.inverse_friends.include?(member)
  end

  def destroy_friendship!(member)
    ActiveRecord::Base.transaction do
      self.friendships.where(friend_id: member.id).destroy_all
      self.inverse_friendships.where(member_id: member.id).destroy_all
      # self.wait_accept_friendships.where(friend_id: member.id).destroy_all
    end
  end
end

app/models/mytag.rb
class Mytag < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates_presence_of :title
  belongs_to :member
  has_many :comments, :as => :commentable
  
  # Plan 拿到 invite_plan，status: false
  has_many :invite_plans, -> { where status: false }
  # 拿到已送出邀請的 member
  has_many :invited_member, through: :invite_plans, source: :member
  
  # 成立的 plan_member
  has_many :confirm_plans, -> { where status: true }, class_name: "InvitePlan" 
  # 拿到已是成員的 member
  has_many :plan_member, through: :confirm_plans, source: :member



  attr_accessor :tag
  acts_as_taggable_on :tags

  # 已經邀請的 member 
  def invited_member?(member)
    self.invited_member.include?(member)
  end

  # 已經是 plan_member
  def plan_member?(member)
    self.plan_member.include?(member)
  end

end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content
  belongs_to :member
  has_many :comments, :as => :commentable

  # attr_accessor :tag_list
  acts_as_taggable_on :tags
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store

  has_many :ware_houses
  has_maany :stores, through: :ware_houses
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  # has_many :products

  has_many :ware_houses
  has_many :products, through: :ware_houses
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/models/ware_house.rb
class WareHouse < ApplicationRecord
  belongs_to :store
  belongs_to :product
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post

  def index
    if params[:id]
      @post = Post.find(params[:id])
    else
      @post = Post.new
    end
  end

  def create
    @post = current_member.posts.build(post_params)
    if params[:commit] == "Save Draft"
      @post.public = false
      if @post.save
        # redirect_to drafts_member_path(current_member)
        flash[:notice] = "儲存草稿"
        redirect_to posts_path
      else
        flash[:alert] = @post.errors.full_messages.to_sentence
        render :index
      end
    else
      @post.public = true
      if @post.save
        flash[:notice] = "發布"
        redirect_to post_path(@post)
      else
        flash[:alert] = @post.errors.full_messages.to_sentence
        render :index
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    if params[:commit] == "Submit"
      @post.public = true
      if @post.update(post_params)
        flash[:notice] = "發布"
        redirect_to posts_path
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        render :index
      end
    else
      @post.public = false
      if @post.update(post_params)
        flash[:notice] = "儲存草稿"
        redirect_to posts_path
      else
        flash[:alert] = @post.errors.full_messages.to_sentence
        render :index
      end
    end
  end

  # def comment
  #   @post = post.find(params[:id])
  #   @comment.user = current_user
  #   @comment = @post.comments.build(comment_params)
  #   @comment.save!
  #   redirect_to post_path(@post)
  # end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  private

  # def comment_params
  #   params.require(:comment).permit(:content)
  # end

  def find_post
    @posts_public = Post.where(public: true)
    @posts_draft = Post.where(public: false)
  end

  def post_params
    params.require(:post).permit(:title, :content, :public, :authority, :tag_list)
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h2>posts_public</h2>
      <ul>
        <% @posts_public.each do |post| %>
          <li>
            <%= link_to post.title, post_path(post) %>
            <%= link_to 'Edit', posts_path(id: post.id) %> <br>
            Tag：<%= post.tag_list %> <br>
            <hr>
            </li>
        <% end %>
      </ul>
    </div>
     <div class="col-sm-6">
      <h2>posts_draft</h2>
      <ul>
        <% @posts_draft.each do |post| %>
          <li>
            <%= link_to post.title, post_path(post) %>
            <%= link_to 'Edit', posts_path(id: post.id) %> <br>
            Tag：<%= post.tag_list %>
            <hr>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm-12 mt-5">
      <%= form_for @post do |f| %>
      <div class="form-group">
          <%= f.text_field :tag_list, value: f.object.tag_list.to_s, placeholder: "Add Tag", class: "form-control bg-light" %>
        </div>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Title", class: "form-control bg-light" %>
        </div>
        <div class="form-group">
          <%= f.text_area :content, placeholder: "Content", class: "form-control bg-light" %>
        </div>
        <div class="form-group">
          <div class="form-check form-check-inline">
            Who Can See
          </div>
          <%= f.radio_button :authority, "All"%> All
          <%= f.radio_button :authority, "Friend"%> Friend
          <%= f.radio_button :authority, "Myself"%> Myself<br/>
        </div>
        <div class="form-group">
          <div class="form-check form-check-inline">
            Category
          </div>
          <div class="form-check form-check-inline">
            <select name="" id="">
              <option value="Taipei">種類下拉式選單</option>
　             <option value="Taoyuan">Ruby</option>
　             <option value="Hsinchu">javaScript</option>
            </select>
            <%#= f.collection_check_boxes :category_ids, Category.all, :id, :name%><br/>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "Save Draft" , class: "btn btn-primary" %>
          <%= f.submit "Submit" , class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
名稱：<%= @post.title %> <br>
內容：<%= @post.content %> <br>
Tags：<%= @post.tag_list %>
<hr>
<h3>留言</h3>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

<hr>

<% @post.comments.each do |comment| %>
  
  留言人：<%= comment.member.name %>
  內容：<%= comment.content %> 
  <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: {confirm: "確定刪除嗎？"} %>
  <hr>

<% end %>