config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
  get 'members/index'
  get 'welcome/index'
  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :candidates do
    member do
      post :vote
    end
  end
  resources :welcomes, only: [:index]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    # member do
      # post :comment
    # end
  end
  resources :plans do
    member do
      post :confirm
      # post :cancelled
      post :join
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :members do
    member do
      get :drafts
      post :change_role
      # post :add_friend
      # post :unfriend
      # post :accept
      # post :ignore
    end
  end
  post "/members/:member_id/plans/:plan_id", to: "members#invite", :as => :invite
  post "/members/:member_id/plans/:plan_id", to: "plans#join", :as => :join
  post "/members/:member_id/plans/:plan_id", to: "members#cancelled", :as => :cancelled

  resources :friendships, only: [:create, :destroy] do
    member do
      post :cancelled
      post :accept
      post :ignore
    end
  end

  root "welcomes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates_presence_of :name, :age, :party, :politics
  has_many :vote_logs, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of  :content
  belongs_to :commentable, :polymorphic => true
  belongs_to :member
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: "Member"
  validates :friend_id, uniqueness: { scope: :member_id }
end

app/models/invite_plan.rb
class InvitePlan < ApplicationRecord
  # validates :member_id, uniqueness: { scope: :plan_id }

  belongs_to :member
  belongs_to :plan
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :plans
  has_many :posts, dependent: :destroy
  
  has_many :comments
  has_many :comments_post, through: :comments, source: :post
  
  # owner 邀請使用者，status: false
  has_many :invite, -> {where status: false}, class_name: "InvitePlan"
  # user 拿到邀請他的 plan，status: false
  has_many :invited_plans, through: :invite, source: :plan

  # user 想加入
  has_many :join, -> {where status: false}, class_name: "InvitePlan"
  # user 想加入
  has_many :join_plan, through: :join, source: :plan


  
  # user been invite
  def invited_plans?(plan)
    self.invited_plans.include?(plan)
  end

  def join_plan?(plan)
    self.join_plan.include?(plan)
  end
  

  # Friendship 的資料表紀錄，menber 是送出邀請的人，friend_id 是被邀請的人。

  # member_id如果是自己，就會去拿 friend_id，並且status 要是 true，的用戶出來
  has_many :friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "member_id", dependent: :destroy
  has_many :friends, through: :friendships
  
  # 從friend_id 如果是自己，就會去拿 member_id出來，並且status 要是 true，的用戶出來
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :member

  # 使用 wait_accept_friendships 送出 create 好友邀請。
  # member_id 如果是自己，就去拿 friend_id，並且status 要是 false，的用戶出來
  has_many :wait_accept_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "member_id", dependent: :destroy
  has_many :waiting_for_accept, through: :wait_accept_friendships, source: :friend
  
  # friend_id 如果是自己，就會去拿 member_id出來，並且status 要是 false，的用戶出來
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friends_request, through: :request_friendships, source: :member

  def all_friends
    (friends + inverse_friends).uniq
  end

  def waiting_for_accept?(member)
    self.waiting_for_accept.include?(member)
  end

  def friends_request?(member)
    self.friends_request.include?(member)
  end

  def friends?(member)
    self.friends.include?(member) || self.inverse_friends.include?(member)
  end

  def destroy_friendship!(member)
    ActiveRecord::Base.transaction do
      self.friendships.where(friend_id: member.id).destroy_all
      self.inverse_friendships.where(member_id: member.id).destroy_all
      # self.wait_accept_friendships.where(friend_id: member.id).destroy_all
    end
  end
end

app/models/mytag.rb
class Mytag < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates_presence_of :title
  belongs_to :member
  has_many :comments, :as => :commentable
  
  # Plan 拿到 invite_plan，status: false
  has_many :invite_plans, -> { where status: false }
  # 拿到已送出邀請的 member
  has_many :invited_member, through: :invite_plans, source: :member
  
  # 成立的 plan_member
  has_many :confirm_plans, -> { where status: true }, class_name: "InvitePlan" 
  # 拿到已是成員的 member
  has_many :plan_member, through: :confirm_plans, source: :member



  attr_accessor :tag
  acts_as_taggable_on :tags

  # 已經邀請的 member 
  def invited_member?(member)
    self.invited_member.include?(member)
  end

  # 已經是 plan_member
  def plan_member?(member)
    self.plan_member.include?(member)
  end

end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content
  belongs_to :member
  has_many :comments, :as => :commentable

  # attr_accessor :tag_list
  acts_as_taggable_on :tags
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store

  has_many :ware_houses
  has_maany :stores, through: :ware_houses
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  # has_many :products

  has_many :ware_houses
  has_many :products, through: :ware_houses
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/models/ware_house.rb
class WareHouse < ApplicationRecord
  belongs_to :store
  belongs_to :product
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    @plans = Plan.all
    @members = Member.all
  end

  def confirm
    # 不管是 申請加入 或 回覆答案 都跑這個action
    @plan = Plan.find(params[:id])
    @confirm = InvitePlan.where(plan_id: params[:id], member_id: current_member)
    @confirm.update(status: true)
    flash[:notice] = "加入plan"
    redirect_back(fallback_location: @plan)
  end

  def cancelled
    @plan = Plan.find(params[:id])
    @confirm = InvitePlan.where(plan_id: params[:id], member_id: current_member).first
    @confirm.destroy
    flash[:notice] = "刪除邀請"
    redirect_back(fallback_location: @plan)
  end

  def join
    @plan = Plan.find(params[:id])
    @join = current_member.invite.build(plan: @plan)

    if @join.save
      flash[:notice] = "申請加入"
      redirect_back(fallback_location: @plan)
    else
      flash[:alert] = @join.errors.full_messages.to_sentence
      redirect_back(fallback_location: @plan)
    end
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.member = current_member
    if @plan.save
      flash[:notice] = "建立計畫 "
      redirect_to plans_path
    else
      flash[:alert] = @plan.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @plan = Plan.find(params[:id])
    @comment = Comment.new
    @members = Member.all
    @invite_plans = InvitePlan.all
    @plan_member = @plan.plan_member
  end

  def invite
    @plan = Plan.find(params[:id])
    @user = User.find(params[])
    # @invite_plan = InvitePlan.new(plan_id: params[:id], member_id: params[:memebr_id])
    @invite_plan = @user.invite_plans.create(plan_id: @plan.id)

    if @invite_plan.save
      flash[:notice] = "邀請 #{member_id} 加入}"
      redirect_to plan_path(@plan)
    else
      flash[:alert] = @invite_plan.errors.full_messages.to_sentence
      redirect_to plan_path(@plan)
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :image, :tag_list)
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/plans/index.html.erb
<div class="row">
  <div class="col-md-12 new-plan">
    <h3><%= link_to '新計畫', new_plan_path %></h3>
    <hr>
  </div>
  
  <div class="plans_list col-md-6">
    <h3>計畫清單</h3>
    <ul>
      <% @plans.each do |plan| %>
        <li><%= link_to plan.title, plan_path(plan) %></li>
        <hr>
      <% end %>
    </ul>  
  </div>

  <div class="members-list col-md-6">
    <h3>使用者清單</h3>
    <ul>
      <% @members.each do |member| %>
        <li><%= link_to member.name, member_path(member) %></li>
        <hr>
      <% end %>
    </ul>  
  </div>
</div>

app/views/plans/new.html.erb
<div class="row">
  <%= form_for @plan do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit %>
  <% end %>
</div>

app/views/plans/show.html.erb
<div class="row">
  <div class="col-md-6">
    
  『<%= @plan.member.name %>』建立 <%= @plan.title %> <br>
  邀請了：從plan 角度出發 <br>
  誰申請加入： 
  <% @plan_member.each do |member| %>
    <%= link_to member.name, member_path(member) %>
  <% end %>
  <br>
  誰報名了：從plan 角度出發
  <hr>

  <h4>回覆/報名</h4>
    <!-- 這裡做user 回覆邀請，報名/取消報名 -->
    <% if current_member.invited_plans?(@plan) %>
      <%= link_to '取消報名', cancelled_path(@plan, current_member), method: :post  %>
    <% else %>  
      <%= link_to '報名', join_plan_path(current_member), method: :post %> 
    <% end %>

    <% if @plan.invited_member?(current_member) %>
      <%= link_to '忽略邀請', cancelled_path(@plan, current_member), method: :post  %>
    <% else %>  
      <%= link_to '加入', confirm_plan_path(current_member), method: :post if @plan.invited_member?(current_member) %> 
    <% end %>  
      
  
  
  
  <hr> 

  <h3>留言</h3>
  <%= form_for [@plan, @comment] do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.submit %>
  <% end %>

  <hr>


  

  <% @plan.comments.each do |comment| %>
    
    留言人：<%= comment.member.name %>
    內容：<%= comment.content %> 
    <%= link_to 'Delete', plan_comment_path(@plan, comment), method: :delete, data: {confirm: "確定刪除嗎？"} %>
    
    <hr>

  <% end %>
  </div>
  <div class="clo-md-6">
  <ul>
    <% @members.each do |member| %>
    <!-- 這裡做審核報名，送出邀請 -->
      <li>
        <%# if @plan.member && member != current_member %>
          <%= link_to member.name, member_path(member) %>
          <% if @plan.invited_member?(member) %>
            已送出邀請
          <% elsif @plan.plan_member?(member) %>
            已是成員
          <% else %>  
            <%= link_to '邀請加入計畫', invite_path(member, @plan), method: :post, class: "btn btn-info btn-sm" %>
          <% end %>  
        <%# end %>  
        <br>
      </li>
    <% end %>
  </ul>
  <hr>
  <% @invite_plans.each do |invite| %>
    <h4>所有在InvitePlan的資料</h4>
    invite_plnas 的id: <%= invite.id %> <br>
    member_id: <%= invite.member_id %> <br>
    plan_id: <%= invite.plan_id %> <br>
    ststus: <%= invite.status %>
    <hr>
  <% end %>

  </div>
</div>