config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
  get 'members/index'
  get 'welcome/index'
  devise_for :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :candidates do
    member do
      post :vote
    end
  end
  resources :welcomes, only: [:index]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    # member do
      # post :comment
    # end
  end
  resources :plans do
    member do
      post :confirm
      # post :cancelled
      post :join
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :members do
    member do
      get :drafts
      post :change_role
      # post :add_friend
      # post :unfriend
      # post :accept
      # post :ignore
    end
  end
  post "/members/:member_id/plans/:plan_id", to: "members#invite", :as => :invite
  post "/members/:member_id/plans/:plan_id", to: "plans#join", :as => :join
  post "/members/:member_id/plans/:plan_id", to: "members#cancelled", :as => :cancelled

  resources :friendships, only: [:create, :destroy] do
    member do
      post :cancelled
      post :accept
      post :ignore
    end
  end

  root "welcomes#index"
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :plans
  has_many :posts, dependent: :destroy
  
  has_many :comments
  has_many :comments_post, through: :comments, source: :post
  
  # owner 邀請使用者，status: false
  has_many :invite, -> {where status: false}, class_name: "InvitePlan"
  # user 拿到邀請他的 plan，status: false
  has_many :invited_plans, through: :invite, source: :plan

  # user 想加入
  has_many :join, -> {where status: false}, class_name: "InvitePlan"
  # user 想加入
  has_many :join_plan, through: :join, source: :plan


  
  # user been invite
  def invited_plans?(plan)
    self.invited_plans.include?(plan)
  end

  def join_plan?(plan)
    self.join_plan.include?(plan)
  end
  

  # Friendship 的資料表紀錄，menber 是送出邀請的人，friend_id 是被邀請的人。

  # member_id如果是自己，就會去拿 friend_id，並且status 要是 true，的用戶出來
  has_many :friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "member_id", dependent: :destroy
  has_many :friends, through: :friendships
  
  # 從friend_id 如果是自己，就會去拿 member_id出來，並且status 要是 true，的用戶出來
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :member

  # 使用 wait_accept_friendships 送出 create 好友邀請。
  # member_id 如果是自己，就去拿 friend_id，並且status 要是 false，的用戶出來
  has_many :wait_accept_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "member_id", dependent: :destroy
  has_many :waiting_for_accept, through: :wait_accept_friendships, source: :friend
  
  # friend_id 如果是自己，就會去拿 member_id出來，並且status 要是 false，的用戶出來
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friends_request, through: :request_friendships, source: :member

  def all_friends
    (friends + inverse_friends).uniq
  end

  def waiting_for_accept?(member)
    self.waiting_for_accept.include?(member)
  end

  def friends_request?(member)
    self.friends_request.include?(member)
  end

  def friends?(member)
    self.friends.include?(member) || self.inverse_friends.include?(member)
  end

  def destroy_friendship!(member)
    ActiveRecord::Base.transaction do
      self.friendships.where(friend_id: member.id).destroy_all
      self.inverse_friendships.where(member_id: member.id).destroy_all
      # self.wait_accept_friendships.where(friend_id: member.id).destroy_all
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!
  def index
    @members = Member.all
  end

  def invite
    @plan = Plan.find(params[:plan_id])
    @member = Member.find(params[:member_id])
    # @invite_plan = InvitePlan.new(plan_id: params[:id], member_id: params[:memebr_id])
    @invite = @member.invite.create(plan: @plan)

    if @invite.save
      flash[:notice] = "邀請 #{params[:member_id]} 加入"
      redirect_to plan_path(@plan)
    else
      flash[:alert] = @invite.errors.full_messages.to_sentence
      redirect_back(fallback_location: plans_path)
    end
  end

   def cancelled
    @plan = Plan.find(params[:id])
    @confirm = InvitePlan.where(plan_id: params[:id], member_id: current_member).first
    @confirm.destroy
    flash[:notice] = "刪除邀請"
    redirect_back(fallback_location: @plan)
  end

  def show
    @member = Member.find(params[:id])
    @friendships = Friendship.all
    @all_friends = @member.all_friends
    @friends = @member.friends
    @inverse_friends = @member.inverse_friends
    @waiting_for_accept = @member.waiting_for_accept
    @friends_request = @member.friends_request
    @invited_plans = @member.invited_plans.all
  end

  # def add_friend
  #   @friendship = current_member.friendships.build(friend_id: params[:id], status: false)

  #   if @friendship.save
  #     flash[:notice] = '已送出邀請'
  #   else
  #     flash[:alert] = @friendship.errors.full_messages.to_sentence
  #   end
  #   redirect_back(fallback_location: members_path)
  # end

  # def unfriend
  #   @member = Member.find(params[:id])
  #   if current_member.friends?(@member)
  #     current_member.destroy_friendship!(@member)
  #     flash[:notice] = 'unfriend'
  #   else
  #     flash[:alert] = 'unfriend failed'
  #   end
  #     redirect_back(fallback_location: root_path)
  # end

  # def accept
  #   @firendship = current_member.friends_request.where(member_id: params[:id])
  #   @friendship.update(status: true)
  #   false[:notice] = "確認為好友"
  # end

  def drafts
    @drafts = current_member.posts.where(public: false)
  end

  def change_role
    # 因為在前台所以多開一個 action 更換權限，update 留給更新 Profile
    # 如果在後台可以直接用update action 就好，
    @member = Member.find(params[:id])
    if @member.email == "admin@example.com"
      flash[:alert] = "不要動！這個帳號是管理員"
      redirect_to members_path
    else
      @member.update(member_params)
      flash[:notice] = "#{@member.name}權限更新為 #{@member.role}"
      redirect_to members_path
    end
  end
  private

  def member_params
    params.require(:member).permit(:role)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/drafts.html.erb
<h2>草稿</h2>
<ul>
  <% @drafts.each do |post| %>
    <li>   
      <%= link_to post.title, post_path(post) %> |
      <%= link_to 'Edit', posts_path(id: post.id) %>
      <%= post.content %>
    </li>
  <% end %>
</ul>

app/views/members/index.html.erb
<div class="row">
  <div class="col-md-4">
    <ul>
      <% @members.each do |member| %>
        <li>
          <%= link_to member.name, member_path(member) %> <span><%= member.role %></span>
          <% if member != current_member %>
            <% if current_member.friends?(member) %>
              <button class="btn btn-success btn-sm"> 已成為好友 </button>
            <% elsif current_member.waiting_for_accept?(member) %>
              <button class="btn btn-light btn-sm" >已送出邀請</button>
            <% elsif current_member.friends_request?(member) %>
              <button class="btn btn-warning btn-sm">對方送出好友邀請</button>
            <% else %>  
              <%= link_to '加好友', friendships_path(friend_id: member), method: :post, data: {"disable-with": "Waiting...."}, class: "btn btn-primary btn-sm" %>
            <% end %>
          <% end %>  
            <div class="change_role form-inline">
              <%= form_for [member], url: change_role_member_path(id: member.id), method: :post do |f| %>
                <%= f.select :role, ["Normal","Admin","VIP"]%>
                <%= f.submit class: "btn btn-primary btn-sm"%>
              <%end%>
            </div>
        </li>
        <br>
      <% end %>
    </ul>
  </div>
</div>

friendship 獨立的路由時，view要傳 friendships_path(friend_id: member)， 
controller 要接收                 (friend_id: params[:friend_id])

friendship 在 member 路由底下，view要傳 add_friend_member_path(member)， 
controller 要接收                         (friend_id: params[:id])

app/views/members/show.html.erb
<div class="member-info">
  <div class="row">
    <div class="col-md-8">
    <p>使用者名稱: <%= @member.name %></p>
    <div class="friendships_table">
      <h6>目前所有 friendships_table 資料有 <%= @friendships.size %> 筆</h6>
        <ul>
        <% @friendships.each do |friend| %>
          <li><p><%= friend.member.name %> 請求加 <%= friend.friend.name %> </p></li>
        <% end %>
        </ul> 
      </h6>
      <hr>
    </div>
    <div class="friends">
      <h6>All_friends： <%= @all_friends.size %></h6>
      <p>要增加刪除鍵時，要給出兩種不同資料</p>
      <p>1. memebr 是我 friend 是對方 -> friends</p>
      <p>2. memebr 是對方 friend 是我 -> inverse_firnships</p>
      <ul>
      <% @all_friends.each do |friend| %>
        <li><%= friend.name %></li>
        <%= link_to '解除好友', friendship_path(friend), method: :delete, data: {confirm: "確定解除好友嗎？", "disable-with": "wating...."}, class: "btn btn-info btn-sm" %>
      <% end %>
    </ul>
      <hr>
    </div>
    <div class="friends">
      <h6>friends 我主動加的好友： <%= @friends.size %></h6>
      <p>紀錄我主動加了誰</p>
      <% @friends.each do |friend| %>
        <%= friend.name %>
      <% end %>
      <hr>
    </div>
    <div class="inverse_friends">
      <h6>inverse_friends 別人家我好友： <%= @inverse_friends.size %></h6>
      <p>紀錄誰主動加了我</p>
      <% @inverse_friends.each do |friend| %>
        <%= friend.name %>
      <% end %>
      <hr>
    </div>
    <div class="waiting_for_accept">
      <h6>waiting_for_accept 自己送出的邀請(可收回邀請)： <%= @waiting_for_accept.size %></h6>
      <p>送出的資料為member是我，friend是當方(為底下each裡的的memebr)。 </p>
      <% @waiting_for_accept.each do |member| %>
        <!-- 這裡的 member 是對方 -->
        <% if current_member != member %>
        <li>
          等待 <%= member.name %> 接受。
          <%= link_to '收回好友邀請', cancelled_friendship_path(member), method: :post, data: {confirm: "確定收回嗎？", "disable-with": "wating...."}, class: "btn btn-info btn-sm" %>
        </li>
        <% end %>
      <% end %>
      <hr>
    </div>
    <div class="friends_request">
      <h6>friends_request 別人送來的邀請(可接受或拒絕)： <%= @friends_request.size %></h6>
      <p>別人送來的請求，member是對方 friend是我</p>
      <% @friends_request.each do |member|%>
        <!-- 這裡的 member 是對方 -->
        <% if current_member != member %>
        <li> 
          <%= member.name %> 送來的好友請求。
          <%= link_to '接受', accept_friendship_path(member), method: :post, data: {"disable-with": "wating...."}, class: 'btn btn-primary btn-sm' %>
          <%= link_to '不接受', ignore_friendship_path(member), method: :post, data: { confirm: "不接受邀請嗎？", "disable-with": "wating...."}, class: 'btn btn-primary btn-sm' %>
        </li>
        <% end %>  
      <% end %>
      <hr>
    </div>
    </div>
    <div class="col-md-4">
      <h3>邀請參加的plan</h3>
      <ul>
        <% @invited_plans.each do |plan| %>
        <li><%= link_to plan.title, plan_path(plan) %></li>
        <% end %>

      </ul>
    </div>
  </div>
</div>
<%= link_to '回到使用者列表', members_path %> <br>